import './globals.css'




export const metadata = {
  title: 'Buffet Crampon - Mobane',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html>
    <head></head>
    <body >
 
      <main>{children}</main>
    </body>
      </html>
  )
}
