import pet from './header'
import blockContent from './blockContent'
import headerinfo from './header-info'
import hero from './hero'
import edition from './edition'
import bois from './bois'
import son from './son'
import video360 from './video360'
import nuances from './nuances'
import specification from './specification'
import pedigre from './pedigre'
import showroom from './showroom'
import footer from './footer'
import pageFooter from './pageFooter'
export const schemaTypes = [blockContent,pet,headerinfo,hero,edition,bois,son, video360, nuances, specification, pedigre, showroom,footer,pageFooter]
